version: "2"

run:
  concurrency: 8
  timeout: 10m
  issues-exit-code: 1
  tests: true

output:
  formats:
    colored-line-number: {}
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    - errcheck
    - goconst
    - goimports
    - gosec
    - govet
    - ineffassign
    - revive
    - unused
