version: "2"

run:
  concurrency: 8
  timeout: 10m
  issues-exit-code: 1
  tests: true

linters:
  enable:
    - errcheck
    - goconst
    - goimports
    - gosec
    - govet
    - ineffassign
    - revive
    - unused

issues:
  exclude:
    - G104
    - exported func .* returns unexported type .*
    - should have a package comment
    - don't use an underscore in package name
